using NpgsqlTypes;

namespace elite_dangerous_colonise.Models.Database_Types
{
    [PgName("HotspotType")]
    public enum HotspotType
    {
        [PgName("Alexandrite")]
        Alexandrite,
        [PgName("Bauxite")]
        Bauxite,
        [PgName("Benitoite")]
        Benitoite,
        [PgName("Bromellite")]
        Bromellite,
        [PgName("Cobalt")]
        Cobalt,
        [PgName("Coltan")]
        Coltan,
        [PgName("Gallite")]
        Gallite,
        [PgName("Gold")]
        Gold,
        [PgName("Grandidierite")]
        Grandidierite,
        [PgName("HydrogenPeroxide")]
        HydrogenPeroxide,
        [PgName("Indite")]
        Indite,
        [PgName("Lepidolite")]
        Lepidolite,
        [PgName("LiquidOxygen")]
        LiquidOxygen,
        [PgName("LithiumHydroxide")]
        LithiumHydroxide,
        [PgName("LowTemperatureDiamond")]
        LowTemperatureDiamond,
        [PgName("MethaneClathrate")]
        MethaneClathrate,
        [PgName("MethanolMonohydrateCrystals")]
        MethanolMonohydrateCrystals,
        [PgName("Monazite")]
        Monazite,
        [PgName("Musgravite")]
        Musgravite,
        [PgName("Opal")]
        Opal,
        [PgName("Osmium")]
        Osmium,
        [PgName("Painite")]
        Painite,
        [PgName("Palladium")]
        Palladium,
        [PgName("Platinum")]
        Platinum,
        [PgName("Praseodymium")]
        Praseodymium,
        [PgName("Rhodplumsite")]
        Rhodplumsite,
        [PgName("Rutile")]
        Rutile,
        [PgName("Samarium")]
        Samarium,
        [PgName("Serendibite")]
        Serendibite,
        [PgName("Silver")]
        Silver,
        [PgName("Tritium")]
        Tritium,
        [PgName("Uraninite")]
        Uraninite,
        [PgName("Water")]
        Water
    }
}
